### ISSUE TITLE
Mongoose error when patching relationships: 'Cast to ObjectID failed for value "[object Object]" at path "parent"'

### ISSUE THREAD

**Issue by adam-ts** [ethanresnick/json-api#106]
When patching a to-one relationship through its relationship link URL (e.g. http://127.0.0.1:3000/people/565db07d2430219d8764a6b0/relationships/parent) [according to the specification](http://jsonapi.org/format/#crud-updating-to-one-relationships), I get errors similar to the following:
``` json
{
  "errors": [
    {
      "status": "400",
      "title": "Cast to ObjectID failed for value \"[object Object]\" at path \"parent\"",
      "paths": [
        "parent"
      ]
    }
  ]
}
```
This happens regardless of what resource identifier object I pass in, even if it's null. For example,
``` json
{
    "data": {
        "id": "565db08b2430219d8764a6b1",
        "type": "people"
    }
}
```
or
``` json
{
    "data": null
}
```
. I first noticed this issue in my own project and then noticed that it happens in json-api-example on the [latest commit](https://github.com/ethanresnick/json-api-example/tree/8cfa51915e101e084fcc1bbf6e25db6c0bc85b6a).

A similar error occurs when attempting to patch a to-many relationship.

The line at which the error occurs seems to be [this one](https://github.com/ethanresnick/json-api/blob/4c6b18891cb8f981bd5213b0aba7362e9f1d8e86/src/db-adapters/Mongoose/MongooseAdapter.js#L257).

Thinking my MongoDB installation might somehow be the problem, I tried installing manually as mentioned at https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/ (my original installation was with Homebrew). That made no difference.

##### Further information
MongoDB version: 3.0.7
Mongoose version: 4.0.8
json-api version: 2.15.5

**Comment by ethanresnick** [comment]
This is a really good catch; thanks so much for reporting it! I've pushed a fix and published the new code to npm. I also added a test case for this, so we shouldn't have regressions in the future.

**Comment by adam-ts** [comment]
Thanks Ethan! I was going to ask about the large response being sent back, but I see you addressed it in that second commit. Everything's working now.

I expect that my company will be using this module a lot, so hopefully I'll have more issues or suggestions for you in the future.

**Comment by ethanresnick** [comment]
That sounds great! Thanks Adam :)
