### ISSUE TITLE
Receiving warning during install: "requires a peer of express@^4.0.0 but none was installed"

### ISSUE THREAD

**Issue by JoshTumath** [ethanresnick/json-api#114]
I installed json-api using the command `npm install json-api --save`. While it did work, I received the following warning:

```
npm WARN json-api@2.15.7 requires a peer of express@^4.0.0 but none was installed.
```

Note that my project has `"express": "^4.13.4"` set in its dependencies.

**Comment by ethanresnick** [comment]
Sorry I never responded to this. On the off-chance it's still an issue, feel free to add a new comment.
