### ISSUE TITLE
Async beforeSave and beforeRender

### ISSUE THREAD

**Issue by caalle** [ethanresnick/json-api#117]
Hi,

Is it possible to do asynchronous operations in `beforeSave` and `beforeRender` hooks?

I'm updating geo-data of a resource before saving it and this operation is async using the `fetch` api.

Eg.

```javascript

beforeSave: function beforeSave(resource, request) {
      return new Promise(resolve => {
        // Do things..
        resolve(resource)
      });
},

```

Is this something that is supported or planned?

**Comment by ethanresnick** [comment]
I believe this is already supported (and there's a [test](https://github.com/ethanresnick/json-api/blob/master/test/integration/create-resource/index.js#L65) for it), but let me know if it doesn't work for some reason.

**Comment by Majo1996** [comment]
Hey did you ever get this working? i'm currently getting geo-data however all my objects are being filled with the same data.

```
beforeRender: function(resource, req, res, superFn) {
    return new Promise((resolve, reject) => {
      maps.getGeoData(resource.adressString).then((response) =>{
        resource.attributes.lat = response.geometry.location.lat;
        resource.attributes.long = response.geometry.location.lng;
        resolve(resource);
      }).catch((err) => {
        resolve(resource);
      });
    });
  },
```

**Comment by ethanresnick** [comment]
@Majo1996 Is your code not working? If so, maybe the issue is `resource.adressString`... should that be `resource.attributes.adressString`? Async beforeRender is definitely supported... as I mention, there's a test for it, and I use it heavily myself.
