### ISSUE TITLE
Readme points to old .js instead of .ts for Mongoose Adapter doc

### ISSUE THREAD

**Issue by themmer** [ethanresnick/json-api#133]
https://github.com/ethanresnick/json-api/blob/master/src/db-adapters/Mongoose/MongooseAdapter.js

to: 

https://github.com/ethanresnick/json-api/blob/master/src/db-adapters/Mongoose/MongooseAdapter.ts

**Comment by ethanresnick** [comment]
Thanks for reporting this! Fixed now.
