### ISSUE TITLE
Filtering collection: Error: Filter criteria must be a list

### ISSUE THREAD

**Issue by EmirGluhbegovic** [ethanresnick/json-api#137]
Hey,

If I run localhost:3114/api/users, all works well. When I run: localhost:3114/api/users?filter=(name, super) I get: Error: Filter criteria must be a list.

I followed the example: /people?filter=(name,Bob)(zip,90210).

Getting: "API Controller caught error Error: Filter criteria must be a list."
Maybe I need to move this another issue?

Regards,
Emir

**Comment by ethanresnick** [comment]
This is very, very strange. The only thing I can think of is that maybe whatever client you're using to make the request is url encoding some character it shouldn't be, and that's confusing the parser.

How are you making the request?

**Comment by EmirGluhbegovic** [comment]
When I run in the browser it runs as expected but I get an empty data array. The data in attributes is defined as name: 'Test'. So when I run /users?filter(name, Test)  I expect 1 result.

Not sure though why its breaking via Postman. Will need to check that out.

**Comment by ethanresnick** [comment]
> when I run /users?filter(name, Test) 

This may just be because you have a space after the comma, so it's trying to match the string " Test". When investigating Postman, my guess is that it's url encoding the `(` and `)`, which it shouldn't be. Anyway, now I'm heading off for real.

**Comment by EmirGluhbegovic** [comment]
You are right, missed that one. The space was the issue causing the empty array. The URL encoding that params will have to check that, but this is a non-issue. Its to do with the tools I am using. Thanks for the help.
