### ISSUE TITLE
Receive relationship resource data in GET request and not just the ID

### ISSUE THREAD

**Issue by EmirGluhbegovic** [ethanresnick/json-api#138]
This is more of a question than an issue. 

I would like to make a request to a parent object and get the children's data back and be able to specify all fields or some fields, not to be limited to just the ID.

Is this possible currently and if not what would be a recommended way to achieve this?

Thanks again.

**Comment by ethanresnick** [comment]
What do you mean by parent and child objects here? Can you give a more detailed example?

This might be possible with query transforms.

**Comment by EmirGluhbegovic** [comment]
If I have the following schema:
```
const userSchema = mongoose.Schema({
	password: {
		type: String,
		required: true,
		select: false,
	},
	email: {
		type: String,
		required: true,
		unique: 'Email address already exists.',
	},
	roles: [
		{
			ref: 'Role',
			type: ObjectId,
			required: true,
		},
	],
});
```
The user contains a relationship to an array of roles.
When I make a request to the user GET api/user
I get back the role ID's in the relationship portion of the json Object. Could I make it so that I can return the role data also and not just the ID in the GET request to the user. So for example I get back

```
{
    "links": {
        "self": "http://localhost:80/users"
    },
    "data": [
        {
            "id": "5a1d3929a261112f2dbdc33a",
            "type": "users",
            "attributes": {
                "email": "test@example.com",
            },
            "links": {
                "self": "/api/users/5a1d3929a261112f2dbdc33a"
            },
            "relationships": {
                "roles": {
                    "data": [
                        {
                            "type": "roles",
                            "id": "5a1d3929a261112f2dbdc322",
                            "name": "admin",
                            "organisation": "Test",
                            "createdAt": "2017/01/01"
                        },
                    ],
                    "links": {
                        "self": "/api/users/5a1d3929a261112f2dbdc33a/relationships/roles"
                    }
                }
            }
        }
    ]
}
```

**Comment by ethanresnick** [comment]
JSON:API supports cases like this with the `?include` query parameter. See http://jsonapi.org/format/#fetching-includes

So you should just be able to to `GET /api/users?include=roles`

**Comment by EmirGluhbegovic** [comment]
@ethanresnick Ye, that did the trick thank you!
