### ISSUE TITLE
Fetch stored types

### ISSUE THREAD

**Issue by EmirGluhbegovic** [ethanresnick/json-api#145]
** DISCLAIMER: These is more questions than an issues, wasn't sure where to post. **

1) Is it possible to fetch all the current stored types?
So if I have the following models: users, rooms, bookings, is there a way to fetch the types ['rooms', 'users', 'bookings'] or to retrieve data from the DB using the type { _type: 'rooms' }, is that part of the functionality exposed/exposable?

2) Is it possible to access the parsed data in my own middleware and not just in beforeRender and beforeSave?
I need to authorize if a user has access to modify a resource before it gets modified and I want to centralize that functionality instead of duplicating the code in each route file in the beforeSave.

Regards,
Emir

**Comment by ethanresnick** [comment]
Hi Emir,

Asking questions here is fine. The number of issues is small enough that it's not a problem, and having the questions and answers public on Github might help others with similar issues.

> Is it possible to fetch all the current stored types?

Yes. The ResourceTypeRegistry has methods for getting information about the registered types. The most directly relevant is the [`typeNames`](https://github.com/ethanresnick/json-api/blob/v3-evolution-over-rewrite/src/ResourceTypeRegistry.ts#L128) method, which returns a list of all the registered type names.

> to retrieve data from the DB using the type { _type: 'rooms' }

I'm not sure what you mean by this. What type of data are you looking for?

> Is it possible to access the parsed data in my own middleware and not just in beforeRender and beforeSave? ... I want to centralize that functionality instead of duplicating the code

Yes. You can do this using the query factory system in v3, which is explained [here](https://github.com/ethanresnick/json-api/tree/v3-evolution-over-rewrite#query-factories). In short, your factory function will see the parsed data in `request.document` and it can throw an error if the user is unauthorized. Something like:

```
const Front = new API.httpStrategies.Express(Controller, Docs, opts);

// Front.customAPIRequest returns a middleware for fulfilling API requests.
// The middleware uses the query factory function provided to build the query
// for fulfilling the request.
const middlewareWithAuthCheck = Front.customAPIRequest({
  queryFactory: (opts) => {
    // opts.request.document is a Document | undefined.
    // If the document exists, opts.request.document.primary holds
    // a Data with the parsed resources/linkage. 
    if(!isAuthorized) {
       throw new APIError(403, undefined, 'Unauthorized');
    }

    return opts.makeQuery(opts); // Promise<Query>
  }
})
```

**Comment by ethanresnick** [comment]
@EmirGluhbegovic Did the above solve your issue? If so, I'll close this.

**Comment by EmirGluhbegovic** [comment]
@ethanresnick Hey, thanks for the advice. Using the customAPIRequest method did solve the issue. 
Concerning the question:

> to retrieve data from the DB using the type { _type: 'rooms' }

Was wondering if there is a way to retrieve data using the types used in the JSON API library with mongoose. If the type is 'users', is there a way to map that to the mongoose collection?

**Comment by ethanresnick** [comment]
> Using the customAPIRequest method did solve the issue.

👍 

> If the type is 'users', is there a way to map that to the mongoose collection?

I think you want to use the static `getModelName` method on MongooseAdapter to converst the json-api type to a model name. Then, you can look up that model on the models dictionary you passed when instantiating the adapter. Once you have the model, you can do `.collection` to get the mongoose collection. So the one liner would be: 

```js
apapterInstance.getModel(MongooseAdapter.getModelName(jsonAPIType)).collection
```
