### ISSUE TITLE
Internal Server Error on Delete

### ISSUE THREAD

**Issue by te-online** [ethanresnick/json-api#147]
When deleting an object the deletion works flawlessly, but the server returns an Internal Server Error. Is this a configuration problem?

Response:
```
{
    "links": {
        "self": "http://localhost/api/users/5a5fd8bf00536fadbdc03819"
    },
    "errors": [
        {
            "status": "500",
            "title": "An unknown error occurred while trying to process this request."
        }
    ]
}
```

The user is gone after the request.

I take any hints on how to debug this problem :-) 

Node version: 9.0.0
json-api version: 3.0.0-beta.1
Request is empty apart from a basic auth header.

**Comment by ethanresnick** [comment]
You can run the library with the environment variable `DEBUG=json-api:*` and that'll give you more detailed error messages. You may be able to figure out the issue then, or you can paste the log here and I'll try to help.

**Comment by te-online** [comment]
Oh, this is helpful, must have missed that option... Thank you, will try that!
________________________________
Von: Ethan<mailto:notifications@github.com>
Gesendet: ‎18.‎01.‎2018 01:48
An: ethanresnick/json-api<mailto:json-api@noreply.github.com>
Cc: Thomas Ebert<mailto:thomas.ebert@te-online.net>; Author<mailto:author@noreply.github.com>
Betreff: Re: [ethanresnick/json-api] Internal Server Error on Delete (#147)


You can run the library with the environment variable DEBUG=json-api:* and that'll give you more detailed error messages. You may be able to figure out the issue then, or you can paste the log here and I'll try to help.

**Comment by te-online** [comment]
Okay, there was a undefined variable in my transformedAPIRequest. Using the debug option it was easy to spot 😄
