### ISSUE TITLE
Proposal to tweak filter syntax

### ISSUE THREAD

**Issue by ethanresnick** [ethanresnick/json-api#160]
I've been thinking about some advanced sorting + filtering use cases this weekend, and concluded that there are some small tweaks to the filter syntax (and expansions to the sort parameter's syntax) that would be good to lock down before v3. The changes I have in mind would require only mechanical tweaks from API clients and adapters.

Thoughts + concerns welcome.

In particular, I'm imagining:

- *Introduce backtick-delimited string literals, and require their use to indicate string values (on the right-hand side of a filter constraint.* Some context: right now we have an unquoted symbol/identifier form in the filter grammar, and a single-quoted string form. That is, there's `(myField,eq,'someval')`, where the left-hand side functions as an identifier to pick out a field by name, rather than a literal string to compare to the value on the right; but the right side value is a literal string. The problem is that, because browsers automatically encode single quotes in query strings<sup>[1]</sup>, we decided to interpret the unquoted symbol form on the right-hand side as a string, so that it would be possible to construct a filtered request just by typing into the URL bar, which is nice for manual testing. That is, we decided to treat `(myField,eq,someval)` as identical to the constraint given earlier. 

  This was a bit inelegant/redundant, as we still needed to keep the single-quoted form, for rare strings that would be ambiguous without quotes (e.g., you need single quotes to express the string "true"). Beyond that, though, this solution makes it impossible to use a field name on the right-hand side. That is, you can have `(myField,in,some%20string)`, but not `('some%20string',in,myField)` because myField will be interpreted as the literal string `'myField'`. Now, allowing field accesses on the right side might be more trouble than it's worth, as it's instead usually possible to create an operator that takes arguments in the reverse order (e.g., perhaps `('some%20string',in,myField)` is better as `(myField,has,'some%sting')`). But, for the general case and for n-ary functions, it'd be very nice to have an unambiguous, non-positional way to differentiate between literal strings and field identifiers/references. To that end, I propose replacing `'`-delimited strings with ```-delimited strings, which works nicely because browsers don't encode backticks and this has precedent in Javascript as a string delimiter. With this change, the only thing clients would have to do to upgrade is surround the right-most value of their filter constraints with backticks, assuming that value is intended as a string. So `(myField,eq,someval)` would become ``(myField,eq,`someVal`)``.

- *Remove the unnecessary layer of wrapping around the list of constraints provided to `and` and `or` operators.* That is: replace `(and,((criteriaA),(criteriaB)))` with simply `(and,(criteriaA),(criteriaB))`. In this second interpretation, the and "function" takes 0-n constraints as its "arguments", rather than it always taking one argument (a list of 0-n) constraints. This generalizes nicely to a rule that says: two-argument filter operators/functions are written with an infix notation (i.e., operator in the middle), while all other constraints are written operator first. This would apply outside the filter param...see below.

- *Allow list expressions in the `sort` parameter*, e.g.: `?sort=(address,distanceFrom,(1223.23,23.20))`. This then works really nicely with the changes above. `address`, as a bare identifier, is a field reference in the same way it would be in other filter constraints or in the sort/include parameter in general (e.g. `?sort=address`). `distanceFrom` is a function that gets infixed, because it's binary, but we could also have n-ary functions like `?sort=(max,fieldA,fieldB,fieldC)`. Ofc, idk how adapters will signal support for, and then implement, these sort functions yet, but I like that the grammar would allow for them in a unified way, and I do think some APIs need this functionality, so adapters should be able to opt-in to supporting it.

[1] The history around why browser's percent encode `'` is actually kinda interesting. The reigning URL standard in the 90s (rfc2396) didn't reserve the single quote as a delimiter, thereby explicitly saying that it:

> can be escaped without changing the semantics of the URI, but this should not be done unless the URI is being used in a context that does not allow the unescaped character to appear.

Browsers went ahead and escaped it, even though they didn't need to, so then they were out of compliance when RFC 3986 came around and tried to reserve it for uses like ours. Nevertheless, with url parsing being a delicate thing to change and browsers having other things to do, this never got updated consistently (see, e.g., [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1040285), which only applied to the URL path); meanwhile, Chrome [decided](https://bugs.chromium.org/p/chromium/issues/detail?id=292740) that leaving the single quote unescaped was more likely to open up XSS vulnerabilities that it was to be useful (fair), and so changed their RFC 3986–compliant implementation to actually escape `'`. Ironically, Firefox had considered that same security issue almost 10 years prior and [decided the same thing](https://bugzilla.mozilla.org/show_bug.cgi?id=376844), but then reversed themselves in the patch linked above. Anyway, I think it's fair to say that we can't rely on the quotes being unescaped.

**Comment by carlbennettnz** [comment]
> Introduce backtick-delimited string literals, and require their use to indicate string values

Definitely agree that strings should be quoted. Having the last arg in `(field,op,value)` be interpreted as a non-string for specific strings (true, false, null, etc) is bound to lead to bugs.

The backticks thing sounds good. Just to confirm, the value in ``(field,eq,`backtick-->%60<--`)`` would be parsed as ``backtick-->`<--``, right?

I'm not sure about allowing field names on the right-hand-side. Are there examples were you can't express your query with the `(field,op,value`) structure? I see how the example you gave makes the query a little more natural, but I'm not sure it's worth it for the additional syntactic complexity, both to the end user and the adapter implementation.

Also, at what point are we just reinventing SQL? :P

> Remove the unnecessary layer of wrapping around the list of constraints provided to `and` and `or` operators

:+1:

> Allow list expressions in the sort parameter

Syntax sounds good. It's backwards compatible too, so it shouldn't need to block v3.

**Comment by ethanresnick** [comment]
Awesome that all these changes sound good to you! I'm gonna go ahead and implement them then.

> Just to confirm, the value in ``(field,eq,`backtick-->%60<--`)`` would be parsed as ``backtick-->`<--``, right?

Correct

> I'm not sure about allowing field names on the right-hand-side. Are there examples were you can't express your query with the (field,op,value) structure?

The only compelling examples I can think of are for filter constraints that compare two fields against one another. E.g., `(field1,gte,field2)` could be quite powerful. I think I'm going to allow this syntactically in v3, but adapters will have some easy way to reject constraints like that if they don't support them.

> Also, at what point are we just reinventing SQL? :P

No comment :P

**Comment by carlbennettnz** [comment]
Awesome, looking forward to trying it out!

**Comment by ethanresnick** [comment]
@carlbennettnz So, it turns out that pretty much every high-level HTTP client in the node ecosystem (at least request, superagent, axios) can't make requests with either unencoded backticks or unencoded single quotes. Details [here](https://github.com/visionmedia/superagent/issues/1367). That's pretty unacceptable to me, so I think the strings need a new delimiter. Here are the candidates that I think look least bad and that I'm pretty sure will work (though I haven't tested extensively yet):

> http://localhost:3000/people?filter=(or,(name,~John Smith~),(name,eq,~Doug Wilson~))"
> http://localhost:3000/people?filter=(or,(name,/John Smith/),(name,eq,/Doug Wilson/))"
> http://localhost:3000/people?filter=(or,(name,!John Smith!),(name,eq,!Doug Wilson!))"
> http://localhost:3000/people?filter=(or,(name,:John Smith:),(name,eq,:Doug Wilson:))"

Do you have a preference?

**Comment by carlbennettnz** [comment]
None of those look great 😢 I don't think any of those immediately make me think "that's a quoted string" in the same way that quotes or backticks would.

What are your design goals with the new syntax? I'm just a little worried it's prioritising ease of *reading* the request over ease of *constructing* it. With v2, a client library like Ember Data could easily convert a filter object into a request.

```js
const orders = await this.store.query('order', {
  simple: {
    total: { $gt: 100 }
  }
})
```

With the new syntax, regardless of string delimination, I would now need to either do a whole lot of error-prone string concatenation, or (more realistically) add a filter query builder that converts the above object into a filter string. The resulting request is definitely more readable — I'm just not sure it's worth the more complex process to build that request.

**Comment by ethanresnick** [comment]
> None of those look great 😢 I don't think any of those immediately make me think "that's a quoted string" in the same way that quotes or backticks would.

Yeah. My hope at this point is actually that superagent et al just get fixed, and then I can stick with backticks. 

> What are your design goals with the new syntax? I'm just a little worried it's prioritising ease of reading the request over ease of constructing it.

Fair enough. I’d say the goals are to come up with a syntax that’s easier to read and to construct by hand, without being any harder to construct automatically. That said, I haven’t actually thought much about what the construction process looks like. For v2 syntax, though, I imagine there’s also a filter builder somewhere doing string concatenation, and it’s not intuitively clear to me why that builder’s algorithm would be any simpler than the one for v3. Do you think it is? Or is the issue just that that serialization logic is already built-in to client-side libraries?

**Comment by ethanresnick** [comment]
Also, tangentially-related, I’ve registered the `@json-api` scope on npm and started to pull out the filter parser into a separate `@json-api/query-parser` package (to make sure there’s a nice contract between the main json-api lib and plugin parsers). So, if the issue is mostly that the serializer for this custom filter format doesn’t exist off the shelf, I’d definitely be game to have a public `@json-api/filter-serializer` that all clients can use

**Comment by ethanresnick** [comment]
Ok, I've finished these changes and will push them soon. 

I stuck with the backticks for delimiting strings, because superagent is now fixed. (The fix hasn't been released yet, but it's merged into master, expected to be released in a week, and available now by referencing the github repo in package.json.) 

I added the `!` as a "backup" string delimiter for clients that absolutely insist on encoding backticks. Hopefully, no one will have to use this. The single quote string syntax is gone.

I also introduced a distinct syntax for data lists (i.e., those lists that aren't intended as expressions to evaluate), using square brackets. In other words:

```
(zip,in,(90210,10012))
``` 

became 

```
(zip,in,[90210,10012])
```

This was important because, otherwise, there was no syntactic way to know that `(90210,10012)` meant "a list of numbers" and not the boolean expression `(90210,eq,10012)`, which is what it would mean in, e.g., `(and,(90210,10012))`. Before, the library had a built-in rule stating that the only times a list should be interpreted as an expression were: 1) at the top level and 2) as an argument to the `and` and `or` operators. But, since a big part of this rework was aimed at making the format more generic, I wanted to have those two cases be differentiable at the parser level, before any library/adapter level contextual information is applied.

**Comment by ethanresnick** [comment]
@carlbennettnz Have you done any work on a query builder to serialize v3 filter/sort constraints? I'm looking to build that now, but thought I'd ask if you already had some code I could use as a starting point.

**Comment by carlbennettnz** [comment]
On the client side? Nah, the syntax is so much more readable that I’ve been getting away with constructing them manually so far.

**Comment by ethanresnick** [comment]
> On the client side? Nah, the syntax is so much more readable that I’ve been getting away with constructing them manually so far.

Ok, gotcha (and glad to hear). I'm probably going to work up something more robust next week, and will publish it when ready.
