### ISSUE TITLE
Remove infix operators in filter syntax?

### ISSUE THREAD

**Issue by ethanresnick** [ethanresnick/json-api#172]
This is an open question for current json-api users: 

Would it be worth it to remove the distinction in the current filter syntax in which binary operators get their operator "infixed" (i.e., placed in the middle, like `(x,gte,4)`) but other operators get their operators placed at the beginning (e.g., `(and,(...),(...))`)? Instead, the operator would *always* be the first item. 

The advantages of this are:

- It becomes easy for a binary operator to add extra, optional operands down the line. E.g., imagine you want to extend the `lte` operator to support "chained comparisons". So, instead of saying `(and,(0,lte,minDistance),(minDistance,lte,maxDistance))`, you want to support something like `(lte,0,minDistance,maxDistance)`. In the current setup, supporting this would change where the parser is expecting `lte` operator to be, because it's no longer a binary a binary operator. So, either you couldn't change it (and would create a new operator instead), or the change would break existing users, or you'd have to complicate the parsing and serialization logic further to support both forms (i.e., `(x,lte,y)` and `(lte,x,y)`).

- Related to the above, the parser and serializer (in progress) already have to special case binary operators. In this simplification, those special cases could be removed, and operators also wouldn't have to be defined with whether they're binary (though perhaps they still could be defined with their arity to enable automatic validation of the length of the arguments list).

- Forcing the infixing of binary operators was intended to offer better usability, and it probably does on the whole. However, the forced infixing sometimes leads to really unreadable results. E.g., there's an operator that takes a center point and a radius and returns a circle value that can be used as an operand to the `geoWithin` operator (to find resource objects inside that circle). Because this operator is binary, it has to be infixed, so you end up with `([0,0],toGeoCircle,100)`. That's pretty cryptic. (The first arg is the center and the second is the radius.) It'd probably be clearer to have `(geoCircle,[0,0],100)`, as that reads more like a standard function call.

The disadvantages are:

- This is a break from the existing format. Big mitigating factor: people could continue to use the current version of the parser package while still updating the json-api lib to the latest version — which is very nice!

- Most binary operators, which are the most common case, probably get a bit less readable, if you accept that that people find it easier to read `(a,gte,b)` than `(gte,a,b)`.

**Comment by ethanresnick** [comment]
Hearing no objections, I'm gonna go ahead and make this change, and publish a new major version of [@json-api/query-parser](https://github.com/ethanresnick/json-api-custom-query-parser) soon. If you want the old behavior, you can explicitly install v2 of the query parser library (`npm i @json-api/query-parser@2.x`) and then configure json-api to use that as your parser:

```ts
import { parseSort, parseFilter } from "@json-api/query-parser";

// Use old parsers
const API = new API.controllers.API(registry, {
  sortParser(legalSortOperators, rawQuery) {
    const paramValue = getQueryParamValue("sort", rawQuery);
    return paramValue && parseSort(paramValue, legalSortOperators);
  },
  filterParser(legalFilterOperators, rawQuery) {
    const paramValue = getQueryParamValue("filter", rawQuery);
    return paramValue && parseFilter(paramValue, legalFilterOperators);
  }
});
```

Note: the code above depends on a `getQueryParamValue` utility function, which the json-api library defines, but isn't considered part of the library's API. You can either: 

1. import it anyway, knowing that your import might break in the future:

   ```ts
   import { getQueryParamValue } from "json-api/build/src/utils/query-parsing"
   ```

2. simply redefine it in your own code: 
    ```ts
    function getQueryParamValue(paramName: string)  {
      return function(queryString: string | undefined) {
        if(typeof queryString === 'undefined') { return undefined; }

        return queryString.split("&").reduce((acc: string | undefined, paramString) => {
            const [rawKey, rawValue] = splitSingleQueryParamString(paramString);
            return rawKey === paramName ? rawValue : acc;
        }, undefined);
      }
    };

    function splitSingleQueryParamString(paramString: string) {
      const bracketEqualsPos = paramString.indexOf("]=");
      const delimiterPos =
        bracketEqualsPos === -1 ? paramString.indexOf("=") : bracketEqualsPos + 1;

      // returning [undecoded key, undecoded value]
      return delimiterPos === -1
        ? [paramString, ""]
        : [paramString.slice(0, delimiterPos), paramString.slice(delimiterPos + 1)];
    }
    ```

**Comment by ethanresnick** [comment]
Thinking about this more, I'm realizing that the problem with the current filter syntax is, more generally, that the special cases around where/if the operator is listed, which are so nice for usability when writing the filter constraints by hand, can lead to pretty problematic bugs when generating the filter constraints programatically.

E.g., imagine an n-ary operator that takes a one or two args, some of which can be identifiers/field references, as in `(nary-op,fieldA,fieldB)`. This works great — unless `fieldA` happens to share the name of a valid binary operator, in which case the parsing suddenly switches from parsing as a use of `nary-op` to parsing as a use of the `fieldA` operator, and there's no way to indicate that that's what you want.

The `eq` shorthand actually suffers from the same problem. ``(field,`value`)`` works great — unless `field` happens to be the name of a (non-binary) operator too, in which case this'll parse as an invocation of that operator.

All this makes me more convinced than ever that the operator needs to be in a consistent spot. 

The obvious answer is to just always put the operator first, as I proposed earlier, but, after sitting with this, I really don't like how it makes the by-far most common cases (binary operators) harder to read. At least to me, `(zip,in,[90210])` is way, way more intuitive than `(in,zip,[90210])`.

So, I had a kinda wacky idea: what if the operator always went in the second spot, but then there was a syntactic form (that could be used with nary operators) to indicate that the operator is the first item instead? My first viable option on that path is prefixing the operator with a colon, which actually seems to be url safe across the myriad of URL specs and implementations (miracle), and which is guaranteed not to conflict with json-api field names. So, it'd look like this:

`(:and,(name,eq,`John`),(salary,gte,100),(dob,gte,1964))`

The parser always looks for the operator second (which is how the infixing works), except when it sees the `:` and so knows to treat and as the operator.

Note: the above would technically be equivalent to/syntactic sugar for:

`((name,eq,`John`),and,(salary,gte,100),(dob,gte,1964))`

The latter looks weird (and hopefully no one would ever write it), but it'd be perfectly legal for consistency. Again, `and` is parsed as the operator because it comes second.

In field constraints that don't have two items, the colon must be used (e.g., `(now)` becomes invalid, but `(:now)` works). Unary operators end up looking backwards by default: `(4,makeNegative)` instead of `(makeNegative,4)`, but this can be fixed with the colon: `(:makeNegative,4)`. Serializers can apply a simple rule: if there are two arguments, put the operator in the middle; in all other cases, use the `:`-prefixed form. I think I like this...

**Comment by ethanresnick** [comment]
Another, more conventional option, would be to invert this. I.e., have the operator always go first, but use `:` as a special infixing syntax. Like ``(and,(name,:eq,`John`)``. Given that almost all of our operators are binary, though, idk if this makes sense.

**Comment by ethanresnick** [comment]
Note: my comment above has been heavily edited and describes the resolution to this issue.

**Comment by ethanresnick** [comment]
This has been addressed in 3.0.0-rc.6. See 0c0b35f

**Comment by ethanresnick** [comment]
@carlbennettnz FYI, there's now a filter/sort param serialization function in the [`@json-api/querystring` package](https://www.npmjs.com/package/@json-api/querystring).

**Comment by carlbennettnz** [comment]
Awesome, thanks!
