### ISSUE TITLE
Support length checking in filter expressions

### ISSUE THREAD

**Issue by olokobayusuf** [ethanresnick/json-api#176]
- For object properties that are arrays or array-like
- Support length equality and inequality checks

**Comment by ethanresnick** [comment]
Is this useful for length equality, or only if inequality checks are supported too? I ask because it looks like mongo supports a length equality check easily with its `$size` operator, but doesn't support length inequality checks at all. I'm not sure about other dbs/adapters.

**Comment by olokobayusuf** [comment]
It won't be useful if we can't check inequalities. I'm closing this issue for now.
