### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by sohamdodia** [ethanresnick/json-api#198]
I am trying to apply a filter like: `GET /media?filter=(user_id, `10`)`, but it is giving this error: 
Invalid filter syntax: Expected field expression but \"(\" found. See jsonapi.js.org for details.

**Comment by ethanresnick** [comment]
You cannot have a space after the comma within a field expression. Please reopen if removing the space doesn't fix the issue.

**Comment by sohamdodia** [comment]
I have tried removing space, still, it is giving me the same error.

**Comment by ethanresnick** [comment]
Can you try it with curl, i.e., ``curl http://HOST_HERE/media?filter=(user_id,`10`)``

**Comment by sohamdodia** [comment]
Not working with the curl also. Giving me the same error which is: Invalid filter syntax: Expected field expression but \"(\" found. See jsonapi.js.org for details

**Comment by ethanresnick** [comment]
Hmm, I'm still not able to reproduce this...that string parses fine for me when I try it against the parser directly. Is there anything sitting in front of your app that could be rewriting the URL? E.g., a reverse proxy?

**Comment by sohamdodia** [comment]
I am creating express app with AWS serverless. I have checked that URL is coming properly by adding a middleware. If you can share a working example, that would be great?

**Comment by ethanresnick** [comment]
When I run the [example app](https://github.com/ethanresnick/json-api-example) locally, ``/people?filter=(user_id,`10`)`` gives no error

**Comment by sohamdodia** [comment]
I am trying to run the example with serverless. And it is throwing the error. With local example, it is working fine.
