### ISSUE TITLE
Express `req.host` deprecation warning

### ISSUE THREAD

**Issue by jacobq** [ethanresnick/json-api#205]
Express warns about `req.host` being deprecated (see exact message below). This appears to be trigged by [the code here](https://github.com/ethanresnick/json-api/blob/master/src/http-strategies/Express.ts#L53). Express 4.x API doc for [`req.hostname` is here](https://expressjs.com/en/api.html#req.hostname). Old 3.x API doc for [`req.host` is here](https://expressjs.com/en/3x/api.html#req.host) --> "Returns the hostname from the “Host” header field (void of portno)." vs the new behavior "Contains the hostname derived from the Host HTTP header...." As far as I can tell, the main difference has to do with effect of proxy trust settings and use of `X-Forwarded-Host`. Is there any reason to still use the deprecated `req.host`? (If it's just to support express < 4.x then it would be easy to do something like `req.hostname || req.host`)

I'm also curious why the linter is told not to warn about this with `// tslint:disable-next-line deprecation`. Any why there's a comment saying that `req.host is broken in express 4; doesn't include the port` since it's not part of the 4.x API and even the 3.x spec says that it's not supposed to include the portno, e.g. example in docs shows this:

```js
// Host: "example.com:3000"
console.dir(req.host)
// => 'example.com'
```

```
express deprecated req.host: Use req.hostname instead at node_modules/json-api/build/src/http-strategies/Express.js:70:102
```

Related to #136

**Comment by jacobq** [comment]
FWIW, if you want to get the port number included in the `Host` header you can always read it directly since ["The req object is an enhanced version of Node’s own request object and supports all built-in fields and methods."](https://expressjs.com/en/api.html#req) --> [`req.headers.body`](https://nodejs.org/api/http.html#http_message_headers)

**Comment by jacobq** [comment]
Just noticed that this very issue is what PR https://github.com/ethanresnick/json-api/pull/197 appears to be aimed at correcting.

**Comment by ethanresnick** [comment]
I'm gonna close this in favor of #197. I need to try to refresh my memory with what was going on here, and then I'll continue the convo in #197.
