### ISSUE TITLE
Multi-level include paths

### ISSUE THREAD

**Issue by nevson** [ethanresnick/json-api#21]
I wanted to experiment a bit with multi-level include paths but noticed that they aren't implemented yet. Maybe you could help me out and tell me which result I should expect when running following query wrt the [json-api example](https://github.com/ethanresnick/json-api-example). In addition to the example please assume that there is a to-many relationship `friends` of type `people` for each `people` type. 

```text
http://127.0.0.1:3000/schools/abc...?include=liaisons,liaisons.friends
```

Would I get a result looking like the following?
```

{
  "data": {
   // ...
    "links": {
      "liaisons": {
        "linkage": [{ "type": "people", "id": "..." }, ...],
        "friends": {
          "linkage": [{"type: "people", "id":"..."}, ...]
        }
      }
    }
  }
}
```

**Comment by nevson** [comment]
Sorry just noticed that this feature is blocked by the same issue as you've mentioned already in ethanresnick/json-api-example#1 , i.e. json-api/json-api#497

**Comment by ethanresnick** [comment]
Yup! That's exactly what I was going to say. #497 really needs to be solved soon :) If you have any thoughts on what the "right" behavior should be, I'd encourage you to read through #497 and then jump in there too!

**Comment by DidelotK** [comment]
Is the problem solved ? I doesn't work for me
I get:
`Multi-level include paths aren't yet supported.`
