### ISSUE TITLE
Please give a workable example

### ISSUE THREAD

**Issue by wanaiqing** [ethanresnick/json-api#218]
Either the example provided in README or the full example in another project is not working.
The former seems missing some code, and the latter always give a 500 error.

**Comment by ethanresnick** [comment]
Hi @wanaiqing, I wish I could help but, truthfully, I'm no longer actively maintaining this library. The example definitely worked when it was written, so it's possible you're using a newer version of some dependency, and that update included a breaking change that the json-api package is not expecting. I would try running the example with a debugger attached (ChatGPT can probably help you do that in your editor of choice) and put a breakpoint where the error is being converted to a 500 response. That might give you better sense into what's going wrong.

**Comment by ethanresnick** [comment]
You can also run the example with a `DEBUG` environment variable set like so: `DEBUG=json-api:*`. That will also give you more information about what's going wrong.

**Comment by wanaiqing** [comment]
> You can also run the example with a `DEBUG` environment variable set like so: `DEBUG=json-api:*`. That will also give you more information about what's going wrong.

Thanks, mongoose outdated, the full example works now.
