### ISSUE TITLE
Investigate Waterline

### ISSUE THREAD

**Issue by ethanresnick** [ethanresnick/json-api#29]
Maybe a single Waterline-based "adapter" could work with mongo and sql databases using existing waterline plugins? https://github.com/balderdashy/waterline

**Comment by cascalheira** [comment]
+1 - this would be great

**Comment by andrewbranch** [comment]
This would be really cool. Honestly the only real reason we're using Mongo at the moment is because it's what this library supports. It would be great to be able to switch to PG on a whim.

**Comment by ethanresnick** [comment]
Closing this, as my sense is that people really only want Mongo and Postgres, rather than Waterline per se, and @carlbennettnz is already working on a Postgres adapter. (Plus, I've heard Waterline isn't always so good about setting up queries to maximize data consistency.)

**Comment by carlbennettnz** [comment]
Sounds good. If other SQL DBs are needed, it wouldn't be hard to add support to my adapter. There's only [one place](https://github.com/carlbennettnz/json-api-knex-adapter/blob/bd68d6972c8c1d03076048cbf324aa2cb6fa6435/src/find/join-to-many-relationships.ts#L31) I know of where I'm using something Postgres-specific. Aside from that, it should support everything Knex supports (MySQL, Maria, SQLite, MSSQL, Oracle). When I get some time, I'll try fixing that issue and getting the test suite to pass on some other DBs.
