### ISSUE TITLE
expect(foo).to.be.an.object is not a thing

### ISSUE THREAD

**Issue by andrewbranch** [ethanresnick/json-api#35]
It should be `expect(foo).to.be.an("object")`

The former will not throw an error. This means there are a lot of tests that aren’t actually testing anything. 😦

**Comment by ethanresnick** [comment]
Good catch! I'll try to fix this when I have a sec. I just need to get the tests running again on my machine. PR welcome too if you have time.

**Comment by ethanresnick** [comment]
Thanks again for catching this Andrew! I just pushed a fix for it and for a bunch of other test suite bugs (some of which represented pretty big logical errors...I must have been really out of it when I was writing that code). Hopefully that will fix the problems with the tests on your machine as well!
