### ISSUE TITLE
Relationship self-links should be contained in links object

### ISSUE THREAD

**Issue by PhilippMi** [ethanresnick/json-api#36]
Relationship links should be [contained in a links object](http://jsonapi.org/format/#document-resource-object-relationships) but json-api currently adds the self-link as a plain string to the relationship object.
Actual:
```javascript
"relationships": {
  "author": {
    "data": { ... },
    "self": "example.com/books/12345/relationships/author"
  }
}
````
Expected:
```javascript
"relationships": {
  "author": {
    "data": { ... },
    "links": {
      "self": "example.com/books/12345/relationships/author"
    }
  }
}
````

**Comment by ethanresnick** [comment]
Thanks for reporting this @PhilippMi! I've fixed it in the latest version of the plugin, 2.6, which is available on NPM. If you're using an older version, make sure to check out the [upgrading instructions](https://github.com/ethanresnick/json-api/blob/master/UPGRADING.md) so you're aware of the other breaking changes (if any) that have been made between the version you're using and 2.6.
