### ISSUE TITLE
Integrate with Koa?

### ISSUE THREAD

**Issue by IanVS** [ethanresnick/json-api#37]
I've been hearing a lot of good things about [Koa](http://koajs.com/), written by the team behind Express.  It doesn't seem to have a json-api serializer yet, from what I can find.  Have you thought about whether this project could also be used with Koa, in addition to Express?  Or if not that, have you thought about writing a serializer similar to this one for Koa?

**Comment by ethanresnick** [comment]
Hi Ian! I've also heard good things about Koa and am quite a fan of generators, so I'd love to integrate with it. I actually designed this library with such integrations in mind, so they're incredibly easy. 

All one has to do is implement four public methods--`apiRequest`, `docsRequest`, `sendResources`, and `sendError`. These methods would be responsible for receiving the request from Koa, translating it to a framework-neutral [Request]() object, passing that into the json-api library, and then using Koa to send the resulting [Response] to the user. Check out the [ExpressStrategy](https://github.com/ethanresnick/json-api/blob/master/src/http-strategies/Express.js) as an example--and note that's the only Express specific code in the whole project. Also, those four public methods are allowed to have whatever signature the framework needs, so the Koa implementation wouldn't need a next parameter, for example.

I don't have time to work on this for at least a couple weeks, but I would welcome a PR if you want to take a stab at it. It seriously shouldn't take more than an hour or two.

**Comment by ethanresnick** [comment]
A Koa strategy has been merged. Thanks @shannonmpoole!
