### ISSUE TITLE
Throw an error if model not found

### ISSUE THREAD

**Issue by andrewbranch** [ethanresnick/json-api#39]
Just a nicety: at the moment, when the adapter's find method gets called, if the type that it tries to find was never provided to the adapter, rather than erroring, it just hangs indefinitely. (I stupidly forgot to add a new model to my `new API.dbAdapters.MongooseAdapter({...})` call, and it took me forever to figure out what was going wrong.)

**Comment by ethanresnick** [comment]
Good catch and, of course, PR welcome! Otherwise, I'll knock this out when I have a spare minute.
