### ISSUE TITLE
sendError always sending 500s

### ISSUE THREAD

**Issue by MichaelBoselowitz** [ethanresnick/json-api#44]
It appears when you use `sendError` like suggested in the [sample project](https://github.com/ethanresnick/json-api-example/blob/b9ba483112bd0a96b56984a93d186b05646c483c/src/index.js#L56) it always hits the default case and sends a general unknown error.

```json
{"errors":[{"status":"500","title":"An unknown error occurred while trying to process this request."}]}
```

After diving through the code a bit it seems to only work if you send it an instance of `APIError`. Is that the case or am I missing something?

If that is so, perhaps the documentation should be updated slightly? Something along the lines of:

```javascript
var API = require('json-api');
var APIError = API.types.Error;
...
apiRouter.use(function(req, res, next) {
    Front.sendError(new APIError(404, undefined, 'Not Found'), req, res);
});
```

**Comment by ethanresnick** [comment]
Thanks Michael! You're totally right.

The sample repo used to return a 404 as expected, but a recent [update](https://github.com/ethanresnick/json-api/commit/f1477c78aa58a1e7d2cb1ffc7922e0e050f4d1df) to the main codebase made it more selective about which errors it passes through in the response, to make sure that implementation details aren't accidentally revealed in error messages.

I've now updated the example repo to bring back the correct behavior.

Cheers,
Ethan
