### ISSUE TITLE
When both ends of a relationship are of the same type, relationships are returned as attributes

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#49]
For example, if I have the following schema

```javascript
var PersonSchema = new Schema({
    parent: {
        type: Schema.ObjectId,
        rel: 'Person'
    }
})

mongoose.model('Person', PersonSchema)
```

and I GET request it, I get something like

```json
{
    "data": [
        {
            "id": "1",
            "type": "person",
            "attributes": {
                "parent": "2"
            },
            "relationships": {}    
        }
    ]
}
```

instead of

```json
{
    "data": [
        {
            "id": "1",
            "type": "person",
            "attributes": {},
            "relationships": {
                "parent": {
                    "id": "2",
                    "type": "person"
                }
            }    
        }
    ]
}
```

**Comment by ethanresnick** [comment]
Hi @carlbennettnz. Thanks for reporting this! I'm having trouble reproducing it though. I've added a relationship just like this to the [example repo](https://github.com/ethanresnick/json-api-example) (i.e. people have a parent with type people), and everything works fine.

If you're still having this issue, can you submit a PR to the example repo that reproduces it?

**Comment by carlbennettnz** [comment]
Sure

**Comment by carlbennettnz** [comment]
Aaaaaand, it was all my fault. I had `rel: 'Account'` instead of `ref: 'Account'` in my schema. Sigh.

Thanks anyway!
