### ISSUE TITLE
How do I remove a particular resource from the response entirely?

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#50]
I can get the `beforeRender` hook to remove specific fields, but I can't seem to get it to remove the resource altogether.

Looking at [the code](https://github.com/ethanresnick/json-api/blob/master/src/steps/apply-transform.js#L17-L19), it seems as though the way to do it is to replace the resource with `undefined`, but that logic is only applied to Collections and returning `undefined` from the `beforeRender` hook just results in a hung request for me.

**Comment by ethanresnick** [comment]
> it seems as though the way to do it is to replace the resource with `undefined`, but that logic is only applied to Collections

Yes, this is intentional, if I remember my thought process correctly. Basically, it's ok to remove a single resource from a response that returns a collection, because the resulting response (just the collection minus one item) is still a valid response. By contrast, a single resource request that doesn't return a resource needs to be an error (probably, but not necessarily, a 404; could also be a 403 etc). 

So, I think the way to do what you want is to have your `beforeRender` transform throw an [`APIError`](https://github.com/ethanresnick/json-api/blob/master/src/types/APIError.js) with the appropriate details. Try that, and let me know if for some reason it doesn't work :)

**Comment by carlbennettnz** [comment]
What I'm doing to getting `/users` which right now returns all users, but should return just the authenticated user (or more, depending on privileges). `beforeRender` is being called once on each of the users found.

Is this what you're talking about with throwing an `APIError`? 

```javascript
var APIError = require('json-api').types.Error

module.exports = {
	urlTemplates: {
		self: 'https://localhost:3000/users/{id}',
		relationship: 'https://localhost:3000/users/{ownerId}/relationships/{path}'
	},

	beforeRender: function(resource) {
		throw new APIError(500, undefined, 'Nope')
	}
}
```

This just hangs for me. Same result if I return the error.

**Comment by ethanresnick** [comment]
Ahh, ok. Then the fact that returning `undefined` doesn't work is just a bug. I think I know where it's coming from, and will push a fix in a sec.

**Comment by ethanresnick** [comment]
This is fixed now, so you should just return `undefined` for the resources you want to remove. See the [commit message](https://github.com/ethanresnick/json-api/commit/6e7b73cbc0671904fe9c6379b83757253b6cad05) if you're curious about what the bug was.

**Comment by carlbennettnz** [comment]
Works perfectly. Thanks so much!

**Comment by ethanresnick** [comment]
Absolutely! Please lmk if you hit any other problems. Ideas for the library are also always welcome!

**Comment by carlbennettnz** [comment]
Do you want me to report hangs when I find them? I've bumped into a few while doing things wrong. Now that I have things set up correctly it's all working fine, but it might be nice to give proper errors in those cases.

**Comment by ethanresnick** [comment]
Yeah, reporting those would be much appreciated! I definitely coded this for the happy path, so the code isn't great about throwing errors where it should (though that's starting to improve as we add more tests).

**Comment by carlbennettnz** [comment]
Sweet, I'll open some more issues. I'll send in a PR or two as well If I manage to get my head around generators

**Comment by ethanresnick** [comment]
Awesome! Thank you! I'll take a look at those issues later tonight :)
