### ISSUE TITLE
Incorrect filtering leads to problems

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#51]
`GET /people?filter[simple][name][going][deeper][gives][errors]` gives a 500 error

It might also be helpful for newcomers if `GET /people?filter[name]=John` gave an error of some sort. It took me a while to find `[simple]`.

**Comment by ethanresnick** [comment]
Noted for when I tackle #15

**Comment by ethanresnick** [comment]
I think the only thing that needs to change here is to issue a clearer error message. That's an easy fix.

**Comment by ethanresnick** [comment]
Closed by 900d6a7
