### ISSUE TITLE
Content-Type: application/json causes a hang

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#59]
I assume there was a reason for accepting it along with `application/vnd.api+json`, but right now any request with a body and that Content-Type hangs for me.

**Comment by ethanresnick** [comment]
You're saying you're getting a hang when you send a request with a body and with `Content-Type: application/json`, right? If so, I can't seem to reproduce this.

On the example repo, I tried the request:

```
POST /people
Content-Type: application/json

{
  "data": {"type": "people"}
}
```

And got back:

```
415 Unsupported Media Type

{
  "errors": [{
    "status": "415",
    "code": null,
    "title": "Invalid Media Type",
    "detail": "The request's Content-Type must be application/vnd.api+json, but you provided: application/json."
  }]
}
```

**Comment by carlbennettnz** [comment]
I can't seem to reproduce on the example repo either, but it's definitely happening in the project I'm using the library on. That probably means it's my fault, but I'll investigate and get back to you.

**Comment by ethanresnick** [comment]
Sounds good :)

**Comment by carlbennettnz** [comment]
So things are breaking on [this line](https://github.com/ethanresnick/json-api/blob/master/src/http-strategies/Express.js#L156). We enter `getRawBody()` but the callback is never called. In my project I'm using [`bodyParser.json()`]. Commenting that line avoids the hang and I get the 415 response like on the example repo.
