### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#62]
May as well do things properly

http://choosealicense.com/

**Comment by ethanresnick** [comment]
Good point! Do you have any opinions here? 

I'm tentatively leaning toward the LGPL, but I'd be open to feedback.

**Comment by carlbennettnz** [comment]
LGPL looks good to me :+1:

**Comment by jacobq** [comment]
Was it your intention to prevent this library from being used in closed-source JS applications? Depending on how you interpret LGPL agreement it seems like bundling an LGPL module with an application (e.g. installed in `node_modules`) requires that application source code to be disclosed...
http://answers.google.com/answers/threadview/id/439136.html
If not, would you consider changing to a more permissive license like [MIT](https://en.wikipedia.org/wiki/MIT_License)?

**Comment by ethanresnick** [comment]
> Was it your intention to prevent this library from being used in closed-source JS applications? 

No, I'd like bundling the library as-is in a closed-source project to be allowed. I'm just asking that people who modify the library share those modifications back. If you LGPL is unclear/ambiguous, I'd be happy to switch to something like https://choosealicense.com/licenses/mpl-2.0/. I'd rather stick with something a bit more copyleft than MIT though

**Comment by jacobq** [comment]
> > Was it your intention to prevent this library from being used in closed-source JS applications?
> 
> No, I'd like bundling the library as-is in a closed-source project to be allowed. I'm just asking that people who modify the library share those modifications back. 

We are not modifying the library at all, so if you're saying that we can bundle it without creating legal problems that should be good enough for us. No need to change license (in fact, it isn't obvious to me whether MPL is more permissive LGPL or not). I am not a lawyer so get nervous when I see stuff about "must disclose source" as I'm never sure which source it applies to (e.g. if I `npm install` some JS library and distribute the corresponding `node_modules` folder with my app, perhaps someone could argue that I've "derived" my app from that module even though that's backwards).

**Comment by ethanresnick** [comment]
> We are not modifying the library at all, so if you're saying that we can bundle it without creating legal problems that should be good enough for us

Yes, that's what I'm saying: feel free to bundle as-is without disclosing your own source
