### ISSUE TITLE
Is the Mongoose 4.0.x peer dependency necessary?

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#73]
I've been using 4.1.0 and haven't noticed any issues. Could we switch to 4.x.x?

**Comment by ethanresnick** [comment]
Yeah, switching to 4.x.x should be fine. Sometimes, projects that claim to use semantic versioning don't actually follow it rigorously in practice (sometimes just by accidentally letting backwards-incompatible changes slip in), so that's a risk, but I'm not too worried about it with Mongoose.
