### ISSUE TITLE
Doesn't work with Firefox

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#78]
[Firefox auto-appends media type parameter 'charset=UTF-8'](https://github.com/json-api/json-api/issues/837).

Do you have a recommended workaround?

**Comment by ethanresnick** [comment]
Blargh. I'm gonna milestone the issue you cited for JSON API 1.1, so that we can get an official fix into the spec soon. For now, I think the fix is to just relax the restriction on the charset parameter in this library, which I can do tomorrow or which I'd accept a PR for.
