### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by andrewbranch** [ethanresnick/json-api#89]
This would be really nice.
http://jsonapi.org/format/#fetching-pagination

**Comment by ethanresnick** [comment]
:+1:

**Comment by jfurie** [comment]
:+1:

**Comment by Immuzov** [comment]
:+1:

**Comment by sambostock** [comment]
:+1:

**Comment by klausbayrhammer** [comment]
:+1:

**Comment by PhilippMi** [comment]
:+1:

**Comment by ubuntuvim** [comment]
Dear @ethanresnick , I would like to ask, json-api support page it? README document has not yet seen a page description, how to use the paging function, my request format `http://localhost:3000/users?page[number]=1&page[size]=3` but can not achieve paging results.

**Comment by ethanresnick** [comment]
@ubuntuvim no, this library doesn't (yet) support pagination

**Comment by ubuntuvim** [comment]
@ethanresnick 
I looked at the recent submission has been a few months ago, I do not know that there is no plan to support pagination?

**Comment by ethanresnick** [comment]
Offset limit pagination has been added in v3. See the v3 readme.
